import { useEffect, useRef, useState } from 'react';
import { ImagePlus, MessageCircle, Music2, Send, Shield, Smile, Trash2, UserRound, X } from 'lucide-react';
import { apiUrl } from '../lib/api';

const time = new Intl.DateTimeFormat('en-PH', { timeZone: 'Asia/Manila', hour: 'numeric', minute: '2-digit', hour12: true });
const EMOJIS = ['😀', '😂', '😍', '😊', '😎', '😢', '😮', '😡', '👍', '👏', '🔥', '✨', '❤️', '🎵', '✅', '🙏'];

export default function ChatDrawer({ socket, onProfile, onPlaySong, openRequest, onUnreadChange, userRole, currentSong }) {
    const [open, setOpen] = useState(false); const [mode, setMode] = useState('community');
    const [messages, setMessages] = useState([]); const [directMessages, setDirectMessages] = useState([]); const [users, setUsers] = useState([]);
    const [recipient, setRecipient] = useState(null); const [text, setText] = useState(''); const [communityUnread, setCommunityUnread] = useState(0); const [directUnread, setDirectUnread] = useState(0);
    const [error, setError] = useState(''); const [imageFile, setImageFile] = useState(null); const [emojiOpen, setEmojiOpen] = useState(false); const end = useRef(null);
    const token = localStorage.getItem('cnxify_token');
    const currentUserId = (() => { try { return JSON.parse(atob(token.split('.')[1])).id; } catch { return null; } })();
    const admins = users.filter((user) => user.role === 'ADMIN' && String(user.id) !== String(currentUserId));

    useEffect(() => {
        if (!token || userRole !== 'ADMIN') return undefined; let cancelled = false;
        fetch(apiUrl('/api/users/directory'), { headers: { Authorization: `Bearer ${token}` } }).then((res) => (res.ok ? res.json() : [])).then((data) => { if (!cancelled) setUsers(data); }).catch(() => {});
        return () => { cancelled = true; };
    }, [token, userRole]);
    useEffect(() => {
        if (!socket) return undefined;
        const received = (message) => { setMessages((items) => [...items, message]); if (!open || mode !== 'community') setCommunityUnread((count) => count + 1); };
        const directReceived = (message) => { const otherId = String(message.sender_id) === String(currentUserId) ? String(message.recipient_id) : String(message.sender_id); if (mode === 'direct' && recipient && String(recipient.id) === otherId) setDirectMessages((items) => [...items, message]); else if (String(message.sender_id) !== String(currentUserId)) setDirectUnread((count) => count + 1); };
        const onDirectHistory = ({ recipientId, messages: history }) => { if (recipient && String(recipient.id) === String(recipientId)) setDirectMessages(history); };
        socket.on('chatHistory', setMessages); socket.on('newMessage', received); socket.on('newDirectMessage', directReceived); socket.on('directHistory', onDirectHistory); socket.on('chatError', setError); socket.on('chatCleared', () => setMessages([]));
        return () => { socket.off('chatHistory', setMessages); socket.off('newMessage', received); socket.off('newDirectMessage', directReceived); socket.off('directHistory', onDirectHistory); socket.off('chatError', setError); socket.off('chatCleared'); };
    }, [socket, open, mode, recipient, currentUserId]);
    useEffect(() => { if (open && socket && mode === 'community') { socket.emit('requestChatHistory'); setCommunityUnread(0); } }, [open, socket, mode]);
    useEffect(() => { if (open && socket && mode === 'direct' && recipient) { socket.emit('requestDirectHistory', recipient.id); setDirectUnread(0); } }, [open, socket, mode, recipient]);
    useEffect(() => { onUnreadChange(communityUnread + directUnread); }, [communityUnread, directUnread, onUnreadChange]);
    useEffect(() => { end.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, directMessages]);
    useEffect(() => { if (openRequest) setOpen(true); }, [openRequest]);

    const sendCommunity = async (share = false) => { const message = share ? '' : text.trim(); if ((!message && !imageFile && !share) || (share && !currentSong)) return; try { let imagePath = null; if (imageFile) { const form = new FormData(); form.append('image', imageFile); const response = await fetch(apiUrl('/api/chat/images'), { method: 'POST', headers: { Authorization: `Bearer ${token}` }, body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error); imagePath = data.image_path; } socket.emit('sendMessage', { message, songId: share ? currentSong.id : null, imagePath }); setText(''); setImageFile(null); } catch (sendError) { setError(sendError.message); } };
    const sendDirect = (share = false) => { const message = share ? '' : text.trim(); if (!recipient || (!message && !(share && currentSong))) return; socket.emit('sendDirectMessage', { recipientId: recipient.id, message, songId: share ? currentSong.id : null }); setText(''); };
    const deleteMessage = async (id) => { try { const response = await fetch(apiUrl(`/api/admin/chat/messages/${id}`), { method: 'DELETE', headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error('Unable to delete message.'); setMessages((items) => items.filter((message) => String(message.id) !== String(id))); } catch (deleteError) { setError(deleteError.message); } };

    return <>
        {open && <button onClick={() => setOpen(false)} className="fixed inset-0 z-40 cursor-default bg-black/50" aria-label="Close chat" />}
        <aside className={`fixed inset-y-0 right-0 z-50 flex w-full max-w-md flex-col border-l border-white/10 bg-[#1c1423] text-white shadow-2xl transition-transform ${open ? 'translate-x-0' : 'translate-x-full'}`}>
            <header className="border-b border-white/10 bg-[#2e2038] p-5"><div className="flex items-center justify-between"><div><b className="text-xs tracking-[.18em] text-[#f6c6d1]">CNXIFY CHAT</b><p className="mt-1 text-xs text-gray-400">{mode === 'community' ? 'Share with your colleagues' : 'Private administrator conversation'}</p></div><button onClick={() => setOpen(false)} className="rounded-lg p-2 hover:bg-white/10"><X /></button></div>{userRole === 'ADMIN' && <div className="mt-4 flex gap-2"><button onClick={() => setMode('community')} className={`flex flex-1 items-center justify-center gap-2 rounded-lg px-3 py-2 text-xs font-bold ${mode === 'community' ? 'bg-[#f6c6d1] text-[#281a30]' : 'bg-white/5 text-gray-300'}`}><MessageCircle size={15} /> Community</button><button onClick={() => setMode('direct')} className={`flex flex-1 items-center justify-center gap-2 rounded-lg px-3 py-2 text-xs font-bold ${mode === 'direct' ? 'bg-[#f6c6d1] text-[#281a30]' : 'bg-white/5 text-gray-300'}`}><Shield size={15} /> Private</button></div>}</header>
            {mode === 'direct' && <div className="border-b border-white/10 p-4"><label className="mb-2 block text-[10px] font-black uppercase tracking-[.16em] text-gray-500">Administrator</label><select value={recipient?.id || ''} onChange={(event) => { const selected = admins.find((user) => String(user.id) === event.target.value); setRecipient(selected || null); setDirectMessages([]); }} className="w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-white outline-none"><option value="">Choose an administrator</option>{admins.map((user) => <option key={user.id} value={user.id}>{user.username}</option>)}</select></div>}
            <main className="flex-1 space-y-4 overflow-y-auto p-5">{error && <p className="rounded-lg bg-red-950/50 p-2 text-xs text-red-200">{error}</p>}
                {mode === 'community' && messages.map((message, index) => <article key={message.id || index} className="group flex gap-2"><button onClick={() => onProfile(message.user_id)} className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#f6c6d1] text-[#281a30]"><UserRound size={15} /></button><div className="min-w-0"><div className="flex gap-2 text-xs"><b>{message.username}</b><time className="text-gray-500">{message.created_at && time.format(new Date(message.created_at))}</time>{userRole === 'ADMIN' && <button onClick={() => deleteMessage(message.id)} className="text-gray-500"><Trash2 size={13} /></button>}</div><div className="mt-1 max-w-[290px] rounded-2xl rounded-tl-sm bg-white/10 px-3 py-2 text-sm">{message.message}{message.image_path && <img src={apiUrl(message.image_path)} alt="Shared in chat" className="mt-2 max-h-60 rounded-xl object-cover" />}</div></div></article>)}
                {mode === 'direct' && !recipient && <p className="pt-10 text-center text-sm text-gray-500">Choose an administrator to open a private conversation.</p>}
                {mode === 'direct' && recipient && directMessages.map((message, index) => <article key={message.id || index} className={`flex ${String(message.sender_id) === String(currentUserId) ? 'justify-end' : 'justify-start'}`}><div className="max-w-[290px] rounded-2xl bg-white/10 px-3 py-2 text-sm"><div className="mb-1 text-[10px] text-gray-500">{String(message.sender_id) === String(currentUserId) ? 'You' : message.sender_name} · {message.created_at && time.format(new Date(message.created_at))}</div>{message.message}{message.song_title && <button onClick={() => onPlaySong({ id: message.song_id, title: message.song_title, artist: message.song_artist, file_path: message.song_file_path, cover_path: message.song_cover_path })} className="mt-2 flex items-center gap-2 text-left text-xs text-[#f6c6d1]"><Music2 size={15} />{message.song_title}</button>}</div></article>)}<div ref={end} /></main>
            <form onSubmit={(event) => { event.preventDefault(); mode === 'community' ? sendCommunity() : sendDirect(); }} className="border-t border-white/10 p-4"><div className="mb-2 flex justify-between text-[11px] text-gray-500"><span>{mode === 'direct' ? (recipient ? `Private chat with ${recipient.username}` : 'Select an administrator first') : imageFile ? `Image ready: ${imageFile.name}` : 'Share with colleagues'}</span><span className="flex items-center gap-2">{mode === 'community' && <label className="cursor-pointer text-[#f6c6d1]"><ImagePlus size={15} /><input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(event) => setImageFile(event.target.files?.[0] || null)} /></label>}<button type="button" onClick={() => setEmojiOpen((value) => !value)} className="text-[#f6c6d1]"><Smile size={15} /></button>{currentSong && mode === 'community' && <button type="button" onClick={() => sendCommunity(true)} className="text-[#f6c6d1]">Share song</button>}{currentSong && recipient && mode === 'direct' && <button type="button" onClick={() => sendDirect(true)} className="text-[#f6c6d1]">Share song</button>}</span></div>{emojiOpen && <div className="mb-2 grid grid-cols-8 gap-1 rounded-xl bg-white/5 p-2">{EMOJIS.map((emoji) => <button type="button" key={emoji} onClick={() => { setText((value) => `${value}${value ? ' ' : ''}${emoji}`); setEmojiOpen(false); }} className="p-1 text-lg">{emoji}</button>)}</div>}<div className="flex gap-2 rounded-xl bg-white/5 p-1"><input value={text} onChange={(event) => setText(event.target.value)} disabled={mode === 'direct' && !recipient} placeholder="Message..." className="min-w-0 flex-1 bg-transparent px-3 text-sm outline-none" /><button disabled={mode === 'direct' && !recipient} className="grid h-9 w-9 place-items-center rounded-lg bg-[#f6c6d1] text-[#281a30] disabled:opacity-50"><Send size={16} /></button></div></form>
        </aside>
    </>;
}
